# Generated by Django 5.2.5 on 2025-08-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='profilePicture',
            field=models.ImageField(default='profilePictures/ordinary.png', upload_to='profilePictures'),
        ),
    ]
