# Generated by Django 5.2.5 on 2025-08-31 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_studentprofile_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='classNumber',
            field=models.IntegerField(default=-1),
        ),
    ]
