# Generated by Django 5.2.5 on 2025-09-01 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_studentprofile_classnumber'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'verbose_name': 'Профил', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='classNumber',
            field=models.IntegerField(default=-1, verbose_name='Номер в класа'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='profilePicture',
            field=models.ImageField(default='profilePictures/ordinary.png', upload_to='profilePictures', verbose_name='Потребителска снимка'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Потребител'),
        ),
    ]
