# Generated by Django 5.2.5 on 2025-09-03 20:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_studentprofile_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='profilePicture',
            field=cloudinary.models.CloudinaryField(default='user-profile_bwwzy0', max_length=255, verbose_name='Профилна снимка'),
        ),
    ]
