# Generated by Django 5.2.5 on 2025-09-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_studentprofile_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='sendEmails',
            field=models.BooleanField(default=False, verbose_name='Изпращане на имейли'),
        ),
    ]
