# Generated by Django 5.2.4 on 2025-08-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageLabel', models.CharField(max_length=255)),
                ('messageText', models.TextField()),
                ('messageImportance', models.IntegerField()),
                ('dateBegin', models.DateTimeField()),
                ('dateEnd', models.DateTimeField()),
            ],
        ),
    ]
