# Generated by Django 5.2.5 on 2025-08-17 19:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Предмет')),
                ('teacher', models.CharField(max_length=255, verbose_name='Учител')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предмети',
            },
        ),
        migrations.AlterModelOptions(
            name='messages',
            options={'verbose_name': 'Съобщение', 'verbose_name_plural': 'Съобщения'},
        ),
        migrations.AlterField(
            model_name='messages',
            name='dateBegin',
            field=models.DateTimeField(verbose_name='Дата на появяне'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='dateEnd',
            field=models.DateTimeField(verbose_name='Дата на изчезване'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='messageImportance',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)], verbose_name='Ниво на съобщението'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='messageLabel',
            field=models.CharField(max_length=255, verbose_name='Заглавие'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='messageText',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('dateDue', models.DateField(verbose_name='Крайна дата')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.subject', verbose_name='Предмет')),
            ],
        ),
    ]
