# Generated by Django 5.2.5 on 2025-08-17 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_subject_alter_messages_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
    ]
