# Generated by Django 5.2.5 on 2025-09-14 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0004_assignment_addedby_assignment_dateadded'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateBegin', models.DateTimeField(verbose_name='Начало на дежурство')),
                ('dateEnd', models.DateTimeField(verbose_name='Край на дежурство')),
                ('userConn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Потребител')),
            ],
            options={
                'verbose_name': 'Дежурство',
                'verbose_name_plural': 'Дежурства',
            },
        ),
    ]
