# Generated by Django 5.2.5 on 2025-09-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0005_dutystudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutystudent',
            name='dateBegin',
            field=models.DateField(verbose_name='Начало на дежурство'),
        ),
        migrations.AlterField(
            model_name='dutystudent',
            name='dateEnd',
            field=models.DateField(verbose_name='Край на дежурство'),
        ),
    ]
