# Generated by Django 5.2.5 on 2025-09-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0006_alter_dutystudent_datebegin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='typeOfAssignment',
            field=models.CharField(choices=[('TW', 'Писмено изпитване'), ('TO', 'Устно изпитване'), ('TEN', 'Входно равнище'), ('TEX', 'Изходно равнище'), ('HW', 'Домашна работа'), ('PR', 'Проект')], default='HW', max_length=255, verbose_name='Тип на заданието'),
        ),
    ]
