# Generated by Django 5.2.5 on 2025-09-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0007_assignment_typeofassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='typeOfAssignment',
            field=models.CharField(choices=[('Писмено изпитване', 'Testwrite'), ('Устно изпитване', 'Testoral'), ('Входно равнище', 'Testentry'), ('Изходно равнище', 'Testexit'), ('Домашна работа', 'Homework'), ('Проект', 'Project')], default='Домашна работа', max_length=255, verbose_name='Тип на заданието'),
        ),
    ]
