# Generated by Django 5.2.5 on 2025-09-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0008_alter_assignment_typeofassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='typeOfAssignment',
            field=models.CharField(choices=[('Писмено изпитване', 'Писмено изпитване'), ('Устно изпитване', 'Устно изпитване'), ('Входно равнище', 'Входно равнище'), ('Изходно равнище', 'Изходно равнище'), ('Домашна работа', 'Домашна работа'), ('Проект', 'Проект')], default='Домашна работа', max_length=255, verbose_name='Тип на заданието'),
        ),
    ]
