# Generated by Django 5.2.5 on 2025-10-14 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0009_alter_assignment_typeofassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('beginDateTime', models.DateTimeField()),
                ('endDateTime', models.DateTimeField()),
                ('questionCode', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choiceText', models.CharField(max_length=255)),
                ('questionConn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.question')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choiceConn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.choices')),
                ('questionConn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.question')),
                ('userConn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
