# Generated by Django 5.2.5 on 2025-10-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0010_question_choices_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questionCode',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
