# Generated by Django 5.2.5 on 2025-09-03 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserMessages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Постове'},
        ),
    ]
